PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS service_categories (id TEXT PRIMARY KEY, name_ar TEXT NOT NULL, code TEXT NOT NULL UNIQUE, active INTEGER NOT NULL DEFAULT 1, sort_order INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS services (id TEXT PRIMARY KEY, category_id TEXT REFERENCES service_categories(id), code TEXT NOT NULL UNIQUE, name_ar TEXT NOT NULL, material_type TEXT, size TEXT, color_mode TEXT, coverage TEXT, unit TEXT NOT NULL, cost_type TEXT NOT NULL DEFAULT 'UNIT', unit_cost REAL, cost_calculation TEXT NOT NULL DEFAULT 'UNIT_COST', sale_calculation TEXT NOT NULL DEFAULT 'PRICING_RULE', active INTEGER NOT NULL DEFAULT 1, notes TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS pricing_rules (id TEXT PRIMARY KEY, service_id TEXT NOT NULL REFERENCES services(id), type TEXT NOT NULL, min_quantity REAL, max_quantity REAL, exact_quantity REAL, sale_price REAL, sale_unit_price REAL, priority INTEGER NOT NULL DEFAULT 0, active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS customers (id TEXT PRIMARY KEY, name TEXT NOT NULL, phone TEXT, email TEXT, company TEXT, notes TEXT, is_cash_customer INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS payment_methods (id TEXT PRIMARY KEY, code TEXT NOT NULL UNIQUE, name_ar TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1, sort_order INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS orders (id TEXT PRIMARY KEY, order_number TEXT NOT NULL UNIQUE, customer_id TEXT REFERENCES customers(id), status TEXT NOT NULL DEFAULT 'NEW', payment_status TEXT NOT NULL DEFAULT 'UNPAID', subtotal REAL NOT NULL DEFAULT 0, discount_type TEXT NOT NULL DEFAULT 'NONE', discount_value REAL NOT NULL DEFAULT 0, discount_amount REAL NOT NULL DEFAULT 0, total REAL NOT NULL DEFAULT 0, total_cost REAL NOT NULL DEFAULT 0, profit REAL NOT NULL DEFAULT 0, profit_margin REAL NOT NULL DEFAULT 0, paid_amount REAL NOT NULL DEFAULT 0, remaining_amount REAL NOT NULL DEFAULT 0, notes TEXT, ordered_at TEXT NOT NULL, cancelled_at TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS order_items (id TEXT PRIMARY KEY, order_id TEXT NOT NULL REFERENCES orders(id), service_id TEXT REFERENCES services(id), service_code_snapshot TEXT NOT NULL, service_name_snapshot TEXT NOT NULL, category_snapshot TEXT, material_type_snapshot TEXT, size_snapshot TEXT, color_mode_snapshot TEXT, unit_snapshot TEXT NOT NULL, quantity REAL NOT NULL, unit_cost_snapshot REAL NOT NULL, total_cost REAL NOT NULL, pricing_rule_id_snapshot TEXT, pricing_rule_snapshot TEXT, unit_sale_price REAL, total_sale_price REAL NOT NULL, profit REAL NOT NULL, profit_margin REAL NOT NULL, manual_price INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS payments (id TEXT PRIMARY KEY, order_id TEXT NOT NULL REFERENCES orders(id), payment_method_id TEXT REFERENCES payment_methods(id), amount REAL NOT NULL, paid_at TEXT NOT NULL, reference TEXT, notes TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS expense_categories (id TEXT PRIMARY KEY, code TEXT NOT NULL UNIQUE, name_ar TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS expenses (id TEXT PRIMARY KEY, category_id TEXT REFERENCES expense_categories(id), expense_date TEXT NOT NULL, description TEXT NOT NULL, amount REAL NOT NULL, notes TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS inventory_items (id TEXT PRIMARY KEY, name TEXT NOT NULL, sku TEXT UNIQUE, unit TEXT NOT NULL, quantity REAL NOT NULL DEFAULT 0, low_stock_threshold REAL NOT NULL DEFAULT 0, purchase_cost REAL NOT NULL DEFAULT 0, active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS inventory_transactions (id TEXT PRIMARY KEY, inventory_item_id TEXT NOT NULL REFERENCES inventory_items(id), type TEXT NOT NULL, quantity REAL NOT NULL, reference_type TEXT, reference_id TEXT, notes TEXT, occurred_at TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS app_settings (key TEXT PRIMARY KEY, value TEXT NOT NULL, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS import_history (id TEXT PRIMARY KEY, version INTEGER NOT NULL UNIQUE, file_name TEXT NOT NULL, imported_at TEXT NOT NULL, imported_by TEXT NOT NULL DEFAULT 'مدير النظام', added_services INTEGER NOT NULL DEFAULT 0, updated_services INTEGER NOT NULL DEFAULT 0, disabled_services INTEGER NOT NULL DEFAULT 0, updated_rules INTEGER NOT NULL DEFAULT 0, result TEXT NOT NULL, error_message TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS backup_history (id TEXT PRIMARY KEY, file_path TEXT NOT NULL, type TEXT NOT NULL, status TEXT NOT NULL, size_bytes INTEGER, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE INDEX IF NOT EXISTS orders_ordered_at_idx ON orders(ordered_at);
CREATE INDEX IF NOT EXISTS orders_customer_id_idx ON orders(customer_id);
CREATE INDEX IF NOT EXISTS order_items_order_id_idx ON order_items(order_id);
CREATE INDEX IF NOT EXISTS order_items_service_id_idx ON order_items(service_id);
CREATE INDEX IF NOT EXISTS payments_order_id_idx ON payments(order_id);

INSERT OR IGNORE INTO customers (id, name, is_cash_customer) VALUES ('cash-customer', 'زبون نقدي', 1);
INSERT OR IGNORE INTO payment_methods (id, code, name_ar, sort_order) VALUES
  ('pm-cash', 'CASH', 'نقدي', 1), ('pm-bit', 'BIT', 'Bit', 2), ('pm-card', 'CARD', 'بطاقة', 3),
  ('pm-bank', 'BANK_TRANSFER', 'تحويل بنكي', 4), ('pm-credit', 'CREDIT', 'آجل', 5), ('pm-other', 'OTHER', 'أخرى', 6);
INSERT OR IGNORE INTO app_settings (key, value) VALUES
  ('printer.name', 'Sandala Printer'), ('currency.code', 'ILS'), ('currency.symbol', '₪'), ('database.schemaVersion', '1');
