import { Boxes, Building2, ChevronDown, LoaderCircle, MessageCircle, PackagePlus, Plus, Store, Trash2, X } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import type { InventoryItemDto, PurchaseRequestDto, SupplierDto } from '../../../shared/contracts'
import { PageHeader } from '../components/PageHeader'
import { getArabicError } from '../utils/errors'
import { formatCurrency, formatNumber } from '../utils/format'

const inventoryAmount = (item: InventoryItemDto) => item.packageEnabled&&item.unitsPerPackage
  ? `${formatNumber(Math.floor(item.quantity/item.unitsPerPackage))} ${item.packageName||'رزمة'} + ${formatNumber(item.quantity%item.unitsPerPackage)} ${item.unit}`
  : `${formatNumber(item.quantity)} ${item.unit}`

export function ShortagesPage() {
  const [suppliers,setSuppliers]=useState<SupplierDto[]>([]), [requests,setRequests]=useState<PurchaseRequestDto[]>([]), [inventory,setInventory]=useState<InventoryItemDto[]>([])
  const [selectedSupplier,setSelectedSupplier]=useState(''), [loading,setLoading]=useState(true), [error,setError]=useState(''), [supplierOpen,setSupplierOpen]=useState(false)
  const [productsSupplier,setProductsSupplier]=useState<SupplierDto|null>(null)
  const [expandedSuppliers,setExpandedSuppliers]=useState<Set<string>>(()=>new Set())
  const [supplierForm,setSupplierForm]=useState({name:'',companyName:'',whatsappPhone:'',productTypes:''}), [saving,setSaving]=useState(false)
  const [addCategoryId,setAddCategoryId]=useState(''), [addItemId,setAddItemId]=useState(''), [addQuantity,setAddQuantity]=useState('1'), [addSupplierId,setAddSupplierId]=useState('')
  const load=async()=>{ setLoading(true); try { const [s,r,i]=await Promise.all([window.desktopApi.shortages.listSuppliers(),window.desktopApi.shortages.listRequests(),window.desktopApi.inventory.list()]); setSuppliers(s);setRequests(r);setInventory(i) } catch(cause){setError(getArabicError(cause,'تعذر تحميل النواقص.'))} finally{setLoading(false)} }
  useEffect(()=>{void load()},[])
  useEffect(()=>{setAddCategoryId('');setAddItemId('');setAddSupplierId('')},[selectedSupplier])
  const visible=requests.filter(r=>!selectedSupplier||r.supplierId===selectedSupplier)
  const grouped=useMemo(()=>suppliers.map(s=>({supplier:s,items:visible.filter(r=>r.supplierId===s.id)})).filter(g=>!selectedSupplier||g.supplier.id===selectedSupplier),[suppliers,visible,selectedSupplier])
  const storeProducts=inventory.filter(i=>!selectedSupplier||i.supplierId===selectedSupplier)
  const productCategories=useMemo(()=>{const categories=new Map<string,string>();for(const item of storeProducts)if(item.categoryId&&item.categoryName)categories.set(item.categoryId,item.categoryName);return [...categories].sort((a,b)=>a[1].localeCompare(b[1],'ar'))},[storeProducts])
  const hasUncategorizedProducts=storeProducts.some(item=>!item.categoryId)
  const categoryProducts=storeProducts.filter(item=>addCategoryId==='uncategorized'?!item.categoryId:item.categoryId===addCategoryId)
  const saveSupplier=async()=>{setSaving(true);setError('');try{await window.desktopApi.shortages.saveSupplier({...supplierForm,productTypes:supplierForm.productTypes.trim()||null});setSupplierOpen(false);setSupplierForm({name:'',companyName:'',whatsappPhone:'',productTypes:''});await load()}catch(cause){setError(getArabicError(cause,'تعذر حفظ التاجر.'))}finally{setSaving(false)}}
  const selectedItem=inventory.find(i=>i.id===addItemId)
  const addRequest=async()=>{if(!selectedItem)return;setSaving(true);try{if(!selectedItem.supplierId){if(!addSupplierId)throw new Error('اختر التاجر لهذا المنتج.');await window.desktopApi.inventory.updateSettings({itemId:selectedItem.id,lowStockThreshold:selectedItem.lowStockThreshold,purchaseCost:selectedItem.purchaseCost,supplierId:addSupplierId,reorderPoint:selectedItem.reorderPoint,minimumOrderQuantity:selectedItem.minimumOrderQuantity,packageEnabled:selectedItem.packageEnabled,packageName:selectedItem.packageName,unitsPerPackage:selectedItem.unitsPerPackage,packagePrice:selectedItem.packagePrice,packageNotes:selectedItem.packageNotes,reorderPackageCount:selectedItem.reorderPackageCount})}await window.desktopApi.shortages.saveRequest({inventoryItemId:selectedItem.id,requestedQuantity:Number(addQuantity),unitPrice:selectedItem.packageEnabled?(selectedItem.packagePrice??0):selectedItem.purchaseCost});setAddItemId('');setAddSupplierId('');await load()}catch(cause){setError(getArabicError(cause,'تعذر إضافة المنتج للطلبية.'))}finally{setSaving(false)}}
  const updateRequest=async(r:PurchaseRequestDto,quantity:number)=>{try{await window.desktopApi.shortages.saveRequest({inventoryItemId:r.inventoryItemId,requestedQuantity:quantity,unitPrice:r.unitPrice});await load()}catch(cause){setError(getArabicError(cause))}}
  const sendWhatsApp=async(supplier:SupplierDto,items:PurchaseRequestDto[])=>{const lines=items.map((item,index)=>`${index+1}. ${item.itemName} — ${formatNumber(item.requestedQuantity)} ${item.unit}`).join('\n');const total=items.reduce((sum,item)=>sum+item.totalPrice,0);const message=`مرحبًا ${supplier.name}،\nنرجو تجهيز طلبية Sandala Printer التالية:\n\n${lines}\n\nالتكلفة التقديرية: ${formatCurrency(total)}\nشكرًا لك.`;try{await window.desktopApi.shortages.openWhatsApp(supplier.id,message)}catch(cause){setError(getArabicError(cause,'تعذر فتح واتساب.'))}}
  const expandSupplier=(supplierId:string)=>setExpandedSuppliers(current=>{const next=new Set(current);next.add(supplierId);return next})
  const toggleSupplier=(supplierId:string)=>setExpandedSuppliers(current=>{const next=new Set(current);if(next.has(supplierId))next.delete(supplierId);else next.add(supplierId);return next})
  return <div className="page shortages-page"><PageHeader title="النواقص والطلبيات" subtitle="تجميع المنتجات الناقصة حسب التاجر وإرسال الطلبية عبر واتساب" action={<button className="primary-button" onClick={()=>setSupplierOpen(true)}><Plus size={17}/> إضافة تاجر</button>}/>{error&&<div className="alert error">{error}</div>}
    <div className="supplier-filter-row"><button className={!selectedSupplier?'active':''} onClick={()=>setSelectedSupplier('')}><Store size={18}/><b>كل التجار</b><span>{formatNumber(requests.length)} منتج في الطلبيات</span></button>{suppliers.map(s=><div className="supplier-filter-card" key={s.id}><button className={selectedSupplier===s.id?'active':''} onClick={()=>{setSelectedSupplier(s.id);expandSupplier(s.id)}}><Building2 size={18}/><b>{s.companyName}</b><span>عرض طلبية التاجر</span></button><button className="supplier-products-link" onClick={()=>setProductsSupplier(s)}><Boxes size={15}/> عرض بضاعته ({formatNumber(s.productCount)})</button></div>)}</div>
    <section className="panel shortage-add-card"><div className="shortage-add-heading"><PackagePlus/><div><b>إضافة منتج للطلبية</b><span>اختر الفئة أولًا، ثم اختر أحد المنتجات التابعة لها.</span></div></div><div className="shortage-add-fields"><select value={addCategoryId} onChange={e=>{setAddCategoryId(e.target.value);setAddItemId('');setAddSupplierId('');setAddQuantity('1')}}><option value="" disabled hidden>اختر الفئة</option>{productCategories.map(([id,name])=><option key={id} value={id}>{name}</option>)}{hasUncategorizedProducts&&<option value="uncategorized">بدون فئة</option>}</select><select value={addItemId} disabled={!addCategoryId} onChange={e=>{const id=e.target.value,item=inventory.find(i=>i.id===id);setAddItemId(id);setAddSupplierId(item?.supplierId??'');setAddQuantity(String(item?.minimumOrderQuantity??1))}}><option value="" disabled hidden>{addCategoryId?'اختر المنتج':'اختر الفئة أولًا'}</option>{categoryProducts.map(i=>{const requested=requests.some(r=>r.inventoryItemId===i.id);return <option key={i.id} value={i.id} disabled={requested}>{i.name}{requested?' — مضاف للطلبية':i.supplierName?` — ${i.supplierName}`:' — يحتاج اختيار تاجر'}</option>})}</select>{selectedItem&&!selectedItem.supplierId&&<select value={addSupplierId} onChange={e=>setAddSupplierId(e.target.value)}><option value="" disabled hidden>اختر التاجر لهذا المنتج</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.companyName} — {s.name}</option>)}</select>}<input type="number" min="0.01" step="any" value={addQuantity} onChange={e=>setAddQuantity(e.target.value)} placeholder={selectedItem?.packageEnabled?`عدد ${selectedItem.packageName||'الرزم'}`:'الكمية'}/><output className="shortage-cost-display"><span>{selectedItem?.packageEnabled?`سعر ${selectedItem.packageName||'الرزمة'}`:'تكلفة الوحدة'}</span><b>{selectedItem?formatCurrency(selectedItem.packageEnabled?(selectedItem.packagePrice??0):selectedItem.purchaseCost,3):'—'}</b></output><button className="primary-button" disabled={!addItemId||saving||(!selectedItem?.supplierId&&!addSupplierId)} onClick={()=>void addRequest()}><Plus size={17}/> إضافة</button></div></section>
    {loading?<div className="panel table-state"><LoaderCircle className="spin"/> جارٍ تحميل الطلبيات...</div>:grouped.length===0?<div className="panel empty-state large"><PackagePlus size={42}/><b>لا توجد نواقص حاليًا</b><span>اربط المنتجات بالتجار وحدد حد إعادة الطلب من صفحة المخزون.</span></div>:grouped.map(({supplier,items})=>{const expanded=expandedSuppliers.has(supplier.id);return <section className={`panel supplier-order-card${expanded?' expanded':''}`} key={supplier.id}><header><button type="button" className="supplier-order-toggle" aria-expanded={expanded} onClick={()=>toggleSupplier(supplier.id)}><Building2/><div><h2>{supplier.companyName}</h2><p>{supplier.name} • <span dir="ltr">{supplier.whatsappPhone}</span> • {formatNumber(items.length)} منتجات</p></div><ChevronDown className="supplier-order-chevron" size={20}/></button><div><strong>{formatCurrency(items.reduce((sum,i)=>sum+i.totalPrice,0))}</strong><button disabled={items.length===0} onClick={()=>void sendWhatsApp(supplier,items)}><MessageCircle size={18}/> إرسال عبر واتساب</button></div></header>{expanded&&(items.length===0?<div className="table-state">لا توجد منتجات مطلوبة من هذا التاجر.</div>:<div className="table-scroll"><table className="data-table shortage-table"><thead><tr><th>المنتج</th><th>المخزون الحالي</th><th>الكمية المطلوبة</th><th>سعر الوحدة</th><th>السعر الكلي</th><th></th></tr></thead><tbody>{items.map(r=><RequestRow key={r.id} request={r} onSave={updateRequest} onDelete={async()=>{await window.desktopApi.shortages.deleteRequest(r.id);await load()}}/>)}</tbody></table></div>)}</section>})}
    {supplierOpen&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setSupplierOpen(false)}}><article className="modal"><header><h2>إضافة تاجر</h2><button className="icon-button" onClick={()=>setSupplierOpen(false)}><X/></button></header><form className="modal-body dialog-form one-column" onSubmit={e=>{e.preventDefault();void saveSupplier()}}><label>اسم التاجر<input required value={supplierForm.name} onChange={e=>setSupplierForm({...supplierForm,name:e.target.value})}/></label><label>اسم الشركة<input required value={supplierForm.companyName} onChange={e=>setSupplierForm({...supplierForm,companyName:e.target.value})}/></label><label>رقم واتساب<input required dir="ltr" placeholder="9725xxxxxxxx" value={supplierForm.whatsappPhone} onChange={e=>setSupplierForm({...supplierForm,whatsappPhone:e.target.value})}/></label><label>نوع المنتجات التي يقدمها<textarea rows={3} value={supplierForm.productTypes} onChange={e=>setSupplierForm({...supplierForm,productTypes:e.target.value})}/></label><div className="dialog-actions"><button type="button" className="secondary-button" onClick={()=>setSupplierOpen(false)}>إلغاء</button><button className="primary-button" disabled={saving}>{saving?'جارٍ الحفظ...':'حفظ التاجر'}</button></div></form></article></div>}
    {productsSupplier&&<SupplierProductsModal supplier={productsSupplier} products={inventory.filter(item=>item.supplierId===productsSupplier.id)} onClose={()=>setProductsSupplier(null)}/>}
  </div>
}

function SupplierProductsModal({supplier,products,onClose}:{supplier:SupplierDto;products:InventoryItemDto[];onClose:()=>void}){return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><article className="modal supplier-products-modal"><header><div><h2>بضاعة {supplier.companyName}</h2><p>{supplier.name} • {supplier.productTypes||'منتجات متنوعة'}</p></div><button className="icon-button" onClick={onClose}><X/></button></header><div className="modal-body">{products.length===0?<div className="empty-state"><Boxes size={36}/><b>لم تُربط بضاعة بهذا التاجر بعد</b><span>يمكن ربط المنتج بالتاجر من صفحة المخزون أو عند إضافته.</span></div>:<div className="supplier-products-scroll"><table className="data-table supplier-products-table"><thead><tr><th>البضاعة</th><th>وحدة الشراء</th><th>المخزون الحالي</th><th>سعر الشراء</th></tr></thead><tbody>{products.map(item=><tr key={item.id}><td><b>{item.name}</b>{item.packageNotes&&<small>{item.packageNotes}</small>}</td><td>{item.packageEnabled?item.packageName:item.unit}</td><td>{inventoryAmount(item)}</td><td dir="ltr">{formatCurrency(item.packageEnabled?(item.packagePrice??0):item.purchaseCost,3)}</td></tr>)}</tbody></table></div>}</div></article></div>}

function RequestRow({request,onSave,onDelete}:{request:PurchaseRequestDto;onSave:(r:PurchaseRequestDto,q:number)=>Promise<void>;onDelete:()=>Promise<void>}){const[q,setQ]=useState(String(request.requestedQuantity));const stock=request.unitsPerPackage?`${formatNumber(Math.floor(request.currentQuantity/request.unitsPerPackage))} ${request.unit} + ${formatNumber(request.currentQuantity%request.unitsPerPackage)} ${request.stockUnit}`:`${formatNumber(request.currentQuantity)} ${request.stockUnit}`;return <tr><td><b>{request.itemName}</b><small>{request.source==='AUTO'?'أضيف تلقائيًا لقرب النفاذ':'أضيف يدويًا'}</small></td><td>{stock}</td><td><input type="number" min="0.01" step="any" value={q} onChange={e=>setQ(e.target.value)} onBlur={()=>void onSave(request,Number(q))}/></td><td><b dir="ltr">{formatCurrency(request.unitPrice,3)}</b></td><td><b dir="ltr">{formatCurrency(Number(q)*request.unitPrice)}</b></td><td><button className="icon-button danger" title="حذف من الطلبية" onClick={()=>void onDelete()}><Trash2 size={17}/></button></td></tr>}
