import { Building2, LoaderCircle, MessageCircle, PackagePlus, Plus, Store, Trash2, X } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import type { InventoryItemDto, PurchaseRequestDto, SupplierDto } from '../../../shared/contracts'
import { PageHeader } from '../components/PageHeader'
import { getArabicError } from '../utils/errors'
import { formatCurrency, formatNumber } from '../utils/format'

export function ShortagesPage() {
  const [suppliers,setSuppliers]=useState<SupplierDto[]>([]), [requests,setRequests]=useState<PurchaseRequestDto[]>([]), [inventory,setInventory]=useState<InventoryItemDto[]>([])
  const [selectedSupplier,setSelectedSupplier]=useState(''), [loading,setLoading]=useState(true), [error,setError]=useState(''), [supplierOpen,setSupplierOpen]=useState(false)
  const [supplierForm,setSupplierForm]=useState({name:'',companyName:'',whatsappPhone:'',productTypes:''}), [saving,setSaving]=useState(false)
  const [addItemId,setAddItemId]=useState(''), [addQuantity,setAddQuantity]=useState('1'), [addPrice,setAddPrice]=useState('0'), [addSupplierId,setAddSupplierId]=useState('')
  const load=async()=>{ setLoading(true); try { const [s,r,i]=await Promise.all([window.desktopApi.shortages.listSuppliers(),window.desktopApi.shortages.listRequests(),window.desktopApi.inventory.list()]); setSuppliers(s);setRequests(r);setInventory(i) } catch(cause){setError(getArabicError(cause,'تعذر تحميل النواقص.'))} finally{setLoading(false)} }
  useEffect(()=>{void load()},[])
  const visible=requests.filter(r=>!selectedSupplier||r.supplierId===selectedSupplier)
  const grouped=useMemo(()=>suppliers.map(s=>({supplier:s,items:visible.filter(r=>r.supplierId===s.id)})).filter(g=>!selectedSupplier||g.supplier.id===selectedSupplier),[suppliers,visible,selectedSupplier])
  const storeProducts=inventory.filter(i=>i.catalogServiceId&&(!selectedSupplier||i.supplierId===selectedSupplier))
  const saveSupplier=async()=>{setSaving(true);setError('');try{await window.desktopApi.shortages.saveSupplier({...supplierForm,productTypes:supplierForm.productTypes.trim()||null});setSupplierOpen(false);setSupplierForm({name:'',companyName:'',whatsappPhone:'',productTypes:''});await load()}catch(cause){setError(getArabicError(cause,'تعذر حفظ التاجر.'))}finally{setSaving(false)}}
  const selectedItem=inventory.find(i=>i.id===addItemId)
  const addRequest=async()=>{if(!selectedItem)return;setSaving(true);try{if(!selectedItem.supplierId){if(!addSupplierId)throw new Error('اختر التاجر لهذا المنتج.');await window.desktopApi.inventory.updateSettings({itemId:selectedItem.id,lowStockThreshold:selectedItem.lowStockThreshold,purchaseCost:Number(addPrice),supplierId:addSupplierId,reorderPoint:selectedItem.reorderPoint,minimumOrderQuantity:selectedItem.minimumOrderQuantity})}await window.desktopApi.shortages.saveRequest({inventoryItemId:selectedItem.id,requestedQuantity:Number(addQuantity),unitPrice:Number(addPrice)});setAddItemId('');setAddSupplierId('');await load()}catch(cause){setError(getArabicError(cause,'تعذر إضافة المنتج للطلبية.'))}finally{setSaving(false)}}
  const updateRequest=async(r:PurchaseRequestDto,quantity:number,price:number)=>{try{await window.desktopApi.shortages.saveRequest({inventoryItemId:r.inventoryItemId,requestedQuantity:quantity,unitPrice:price});await load()}catch(cause){setError(getArabicError(cause))}}
  const sendWhatsApp=async(supplier:SupplierDto,items:PurchaseRequestDto[])=>{const lines=items.map((item,index)=>`${index+1}. ${item.itemName} — ${formatNumber(item.requestedQuantity)} ${item.unit}`).join('\n');const total=items.reduce((sum,item)=>sum+item.totalPrice,0);const message=`مرحبًا ${supplier.name}،\nنرجو تجهيز طلبية Sandala Printer التالية:\n\n${lines}\n\nالتكلفة التقديرية: ${formatCurrency(total)}\nشكرًا لك.`;try{await window.desktopApi.shortages.openWhatsApp(supplier.id,message)}catch(cause){setError(getArabicError(cause,'تعذر فتح واتساب.'))}}
  return <div className="page shortages-page"><PageHeader title="النواقص والطلبيات" subtitle="تجميع المنتجات الناقصة حسب التاجر وإرسال الطلبية عبر واتساب" action={<button className="primary-button" onClick={()=>setSupplierOpen(true)}><Plus size={17}/> إضافة تاجر</button>}/>{error&&<div className="alert error">{error}</div>}
    <div className="supplier-filter-row"><button className={!selectedSupplier?'active':''} onClick={()=>setSelectedSupplier('')}><Store size={18}/><b>كل التجار</b><span>{formatNumber(requests.length)} منتج</span></button>{suppliers.map(s=><button key={s.id} className={selectedSupplier===s.id?'active':''} onClick={()=>setSelectedSupplier(s.id)}><Building2 size={18}/><b>{s.companyName}</b><span>{formatNumber(s.productCount)} منتجات — عرض منتجاته</span></button>)}</div>
    <section className="panel shortage-add-card"><div><PackagePlus/><div><b>إضافة منتج للطلبية</b><span>تظهر هنا منتجات البيع المسجلة في قسم الخدمات والمنتجات، بما فيها المنتجات التي ستضيفها لاحقًا.</span></div></div><select value={addItemId} onChange={e=>{const id=e.target.value,item=inventory.find(i=>i.id===id);setAddItemId(id);setAddSupplierId(item?.supplierId??'');setAddPrice(String(item?.purchaseCost??0));setAddQuantity(String(item?.minimumOrderQuantity??1))}}><option value="">اختر المنتج</option>{storeProducts.map(i=>{const requested=requests.some(r=>r.inventoryItemId===i.id);return <option key={i.id} value={i.id} disabled={requested}>{i.name}{requested?' — مضاف للطلبية':i.supplierName?` — ${i.supplierName}`:' — يحتاج اختيار تاجر'}</option>})}</select>{selectedItem&&!selectedItem.supplierId&&<select value={addSupplierId} onChange={e=>setAddSupplierId(e.target.value)}><option value="">اختر التاجر لهذا المنتج</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.companyName} — {s.name}</option>)}</select>}<input type="number" min="0.01" step="any" value={addQuantity} onChange={e=>setAddQuantity(e.target.value)} placeholder="الكمية"/><input type="number" min="0" step="0.001" value={addPrice} onChange={e=>setAddPrice(e.target.value)} placeholder="سعر الوحدة"/><button className="primary-button" disabled={!addItemId||saving||(!selectedItem?.supplierId&&!addSupplierId)} onClick={()=>void addRequest()}><Plus size={17}/> إضافة</button></section>
    {loading?<div className="panel table-state"><LoaderCircle className="spin"/> جارٍ تحميل الطلبيات...</div>:grouped.length===0?<div className="panel empty-state large"><PackagePlus size={42}/><b>لا توجد نواقص حاليًا</b><span>اربط المنتجات بالتجار وحدد حد إعادة الطلب من صفحة المخزون.</span></div>:grouped.map(({supplier,items})=><section className="panel supplier-order-card" key={supplier.id}><header><div><Building2/><div><h2>{supplier.companyName}</h2><p>{supplier.name} • <span dir="ltr">{supplier.whatsappPhone}</span> • {supplier.productTypes||'منتجات متنوعة'}</p></div></div><div><strong>{formatCurrency(items.reduce((sum,i)=>sum+i.totalPrice,0))}</strong><button disabled={items.length===0} onClick={()=>void sendWhatsApp(supplier,items)}><MessageCircle size={18}/> إرسال عبر واتساب</button></div></header>{items.length===0?<div className="table-state">لا توجد منتجات مطلوبة من هذا التاجر.</div>:<div className="table-scroll"><table className="data-table shortage-table"><thead><tr><th>المنتج</th><th>المخزون الحالي</th><th>الكمية المطلوبة</th><th>سعر الوحدة</th><th>السعر الكلي</th><th></th></tr></thead><tbody>{items.map(r=><RequestRow key={r.id} request={r} onSave={updateRequest} onDelete={async()=>{await window.desktopApi.shortages.deleteRequest(r.id);await load()}}/>)}</tbody></table></div>}</section>)}
    {supplierOpen&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setSupplierOpen(false)}}><article className="modal"><header><h2>إضافة تاجر</h2><button className="icon-button" onClick={()=>setSupplierOpen(false)}><X/></button></header><form className="modal-body dialog-form one-column" onSubmit={e=>{e.preventDefault();void saveSupplier()}}><label>اسم التاجر<input required value={supplierForm.name} onChange={e=>setSupplierForm({...supplierForm,name:e.target.value})}/></label><label>اسم الشركة<input required value={supplierForm.companyName} onChange={e=>setSupplierForm({...supplierForm,companyName:e.target.value})}/></label><label>رقم واتساب<input required dir="ltr" placeholder="9725xxxxxxxx" value={supplierForm.whatsappPhone} onChange={e=>setSupplierForm({...supplierForm,whatsappPhone:e.target.value})}/></label><label>نوع المنتجات التي يقدمها<textarea rows={3} value={supplierForm.productTypes} onChange={e=>setSupplierForm({...supplierForm,productTypes:e.target.value})}/></label><div className="dialog-actions"><button type="button" className="secondary-button" onClick={()=>setSupplierOpen(false)}>إلغاء</button><button className="primary-button" disabled={saving}>{saving?'جارٍ الحفظ...':'حفظ التاجر'}</button></div></form></article></div>}
  </div>
}

function RequestRow({request,onSave,onDelete}:{request:PurchaseRequestDto;onSave:(r:PurchaseRequestDto,q:number,p:number)=>Promise<void>;onDelete:()=>Promise<void>}){const[q,setQ]=useState(String(request.requestedQuantity)),[p,setP]=useState(String(request.unitPrice));return <tr><td><b>{request.itemName}</b><small>{request.source==='AUTO'?'أضيف تلقائيًا لقرب النفاذ':'أضيف يدويًا'}</small></td><td>{formatNumber(request.currentQuantity)} {request.unit}</td><td><input type="number" min="0.01" step="any" value={q} onChange={e=>setQ(e.target.value)} onBlur={()=>void onSave(request,Number(q),Number(p))}/></td><td><input type="number" min="0" step="0.001" value={p} onChange={e=>setP(e.target.value)} onBlur={()=>void onSave(request,Number(q),Number(p))}/></td><td><b dir="ltr">{formatCurrency(Number(q)*Number(p))}</b></td><td><button className="icon-button danger" title="حذف من الطلبية" onClick={()=>void onDelete()}><Trash2 size={17}/></button></td></tr>}
